[package]
name = "cryptlib"
version = "0.1.1"
edition = "2021"

[dependencies]
bcrypt = "0.15.1"
serde = {version="1.0.213", features = ["derive"]}
serde_json = "1.0.132"
thiserror = "1.0.65"
walkdir = "2.5.0"
